version: "3.9"
services:
  redis:
    container_name: redis-container
    image: "redis:alpine"
    ports:
      - "6379:6379"
  web:
    container_name: web
    depends_on:
      - redis
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      PORT: 5000
      REDIS_HOST: redis
      REDIS_PORT: 6379
      # NODE_ENV: production
    command: yarn start:prod
