version: "3.9"
services:
  redis:
    container_name: redis-container
    image: "redis:alpine"
    ports:
      - "6379:6379"
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      PORT: 5000
      NODE_ENV: production
      APP_ENV: production
    command: yarn start:prod
